FROM golang:1.21-alpine AS builder
WORKDIR /usr/src/app
COPY desafio.go ./
COPY . .
RUN go build -v -o /usr/local/bin/app ./...
CMD ["app"]

FROM scratch
WORKDIR /
COPY --from=builder /usr/local/bin/app .
CMD ["/app"]
